<style xmlns="http://www.w3.org/1999/html">
    label {
        display: inline-block;
        width: 140px;
        text-align: right;
    }​
         .field-set input {
             margin: 10px;
     }
</style>
<h1>Add Additional Information</h1>
<input type="hidden" name="admin_hidden" value="hidden_admin">
<div class="field-set"><label>Invoice Number :</label>
    <input name="invoice_number" type="text">
</div>
<div class="field-set">
    <label>Customer Number :</label>
    <input name="customer_number" type="text">
</div>
<div class="field-set">
    <label>Your Contact :</label>
    <input name="your_contact" type="text">
</div>
<div class="field-set">
    <label>Payment Term :</label>
    <input name="payment_term" type="text">
</div>
<div class="field-set">
    <label>Comment :</label>
    <input name="comment" type="text">
</div>
<div class="field-set">
    <label>Post Date :</label>
    <input name="posting_date" type="text">
</div>
<div class="field-set">
    <label>Additional Charges:</label>
    <input name="additional_charges" type="text">
</div>
<div class="field-set">
    <label>Discount Charge :</label>
    <input name="discount_charge" type="text">
</div>
<div class="field-set">
    <label>Environmental Fees :</label>
    <input name="environmental_fees" type="text">
</div>
<br />