<style>
    .evn{
        width:100%;height:auto;padding:10px;
    }
    .odd{
        width:100%;height:auto;background-color:#eeeeee;padding:10px;
    }
</style>
<div style="" class="evn">
    Invoice Number
<p style="float:right">
<?php 
if ($block->customSapInvoiceData()->getData('invoice_number') != null) {
    print_r($block->customSapInvoiceData()->getData('invoice_number'));
} else {
    echo "xxx";
}
?>
</p>
</div>

<div style="" class="odd">
Customer Number
<p style="float:right">
<?php 
if ($block->customSapInvoiceData()->getData('customer_number') != null) {
    print_r($block->customSapInvoiceData()->getData('customer_number'));
} else {
    echo "xxx";
}
?>
</p>
</div>

<div style="" class="evn">
Your Contact
<p style="float:right">
<?php 
if ($block->customSapInvoiceData()->getData('your_contact') != null) {
    print_r($block->customSapInvoiceData()->getData('your_contact'));
} else {
    echo "xxx";
}
?>
</p>
</div>

<div style="" class="odd">
Payment Term
<p style="float:right">
<?php 
if ($block->customSapInvoiceData()->getData('payment_term') != null) {
    print_r($block->customSapInvoiceData()->getData('payment_term'));
} else {
    echo "xxx";
}
?>
</p>
</div>

<div style="" class="evn">
Comment
<p style="float:right"><?php 
if ($block->customSapInvoiceData()->getData('comment') != null) {
    print_r($block->customSapInvoiceData()->getData('comment'));
} else {
    echo "xxx";
}
?>
</p>
</div>
<div style="" class="odd">
    Posting Date
    <p style="float:right">
        <?php
        if ($block->customSapInvoiceData()->getData('posting_date') != null) {
            print_r($block->customSapInvoiceData()->getData('posting_date'));
        } else {
            echo "xxx";
        }
        ?>
    </p>
</div>
<div style="" class="evn">
    Additional Charges
    <p style="float:right"><?php
        if ($block->customSapInvoiceData()->getData('additional_charges') != null) {
            print_r($block->customSapInvoiceData()->getData('additional_charges'));
        } else {
            echo "xxx";
        }
        ?>
    </p>
</div>
<div style="" class="odd">
    Discount Charge
    <p style="float:right">
        <?php
        if ($block->customSapInvoiceData()->getData('discount_charge') != null) {
            print_r($block->customSapInvoiceData()->getData('discount_charge'));
        } else {
            echo "xxx";
        }
        ?>
    </p>
</div>
<div style="" class="evn">
    Environmental Fees
    <p style="float:right"><?php
        if ($block->customSapInvoiceData()->getData('environmental_fees') != null) {
            print_r($block->customSapInvoiceData()->getData('environmental_fees'));
        } else {
            echo "xxx";
        }
        ?>
    </p>
</div>