<?php
/**
 * Mega Menu HTML File.
 *
 * @category  Site Search & Navigation
 * @package   Root_Mega_Menu
 * @author    Developer RootwaysInc <developer@rootways.com>
 * @copyright 2017 Rootways Inc. (https://www.rootways.com)
 * @license   Rootways Custom License
 * @link      https://www.rootways.com/shop/media/extension_doc/license_agreement.pdf
*/
$categories = $this->getStoreCategories(true,false,true);
$categoryHelper = $this->getCategoryHelper();
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$helper = $this->helper('Rootways\Megamenu\Helper\Data');
$storeManager = $_objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$base_url = $storeManager->getStore()->getBaseUrl();

if ( $helper->getConfig('rootmegamenu_option/general/enable') == 1 ) { ?>    
    <div class="page-main">
        <nav class="rootmenu" data-action="navigation">
            <ul id="rw-menutop" class="mobile-sub rootmenu-list">
                <?php if ($helper->getConfig('rootmegamenu_option/general/show_home_link') == 1) { ?>
                    <li><a <?php if ( $this->getIsHomePage() == 1 ) { echo 'class="active"'; } ?>href="<?php echo $base_url;?>" title="Home" ><span class="fa fa-home homeicon"></span><em><?php echo __('Home');?></em></a></li>
                <?php } ?> 
                <?php
                $view_more_array = array();
                $main_cat_cnt = 1;
                foreach($categories as $category) {

                    echo $this->getCustomLinks($category->getId());

                    if ( $helper->getConfig('rootmegamenu_option/general/show_view_more') == 1 ) {
                        if ( $helper->getConfig('rootmegamenu_option/general/view_more') == '' ) {
                            $view_more_after = 8;
                        } else { 
                            $view_more_after = $helper->getConfig('rootmegamenu_option/general/view_more');
                        }
                        if ($main_cat_cnt > $view_more_after) { 
                            $view_more_array[$category->getName()] = $category->getURL();
                            continue;
                        }
                    }

                    $main_category_load = $_objectManager->create('Magento\Catalog\Model\Category')->load($category->getId());
                    if (!$category->getIsActive()) {
                        continue;
                    }
                    $active_cls = '';
                    $request = $_objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
                    if ($request->getFullActionName() == 'catalog_category_view') {
                       $active_cls = $this->_getMenuItemAttributes($category);
                    } ?>
                    <li>
                       <a class="<?php echo $active_cls; ?>" href="<?php echo $categoryHelper->getCategoryUrl($main_category_load) ?>">
                            <?php if ( $helper->getConfig('rootmegamenu_option/general/topmenu_icon') == 1 && $main_category_load->getImageUrl() != '') { ?>
                                <span class="main-category-name">
                                    <i class="main-category-icon"><img src="<?php echo $main_category_load->getImageUrl(); ?>"/></i>
                                    <em><?php echo $category->getName();?></em>
                                </span>
                            <?php } else {
                                echo $main_category_load->getName();
                            } ?>
                        </a>
                        <?php
                        if ($main_category_load->getMegamenuType() == 1) {
                            echo $this->simpletMenu($category);
                        } elseif ($main_category_load->getMegamenuType() == 2) {
                            echo $this->megadropdown($category);
                        } elseif ($main_category_load->getMegamenuType() == 3) {
                            echo $this->dropdownTitle($category);
                        } elseif ($main_category_load->getMegamenuType() == 4) {
                            echo $this->halfMenu($category);
                        } elseif ($main_category_load->getMegamenuType() == 5) {
                             echo $this->halfTitleMenu($category);
                        } elseif ($main_category_load->getMegamenuType() == 6) {
                             echo $this->fullWidthMenu($category);
                        } elseif ($main_category_load->getMegamenuType() == 7) {
                            echo $this->fullTitleMenu($category);
                        } elseif ($main_category_load->getMegamenuType() == 8) {
                            echo $this->tabMenu($category);
                        } elseif ($main_category_load->getMegamenuType() == 9) {
                            echo $this->tabHorizontal($category);
                        } elseif ($main_category_load->getMegamenuType() == 10) {
                            echo $this->productMenu($category);
                        } else {
                            echo $this->simpletMenu($category);
                        }
                        ?>
                    </li>
                    <?php $main_cat_cnt++; ?>
                <?php } ?>

                <?php echo $this->getCustomLinks(false);?>

                <?php if ($helper->getConfig('rootmegamenu_option/general/show_contactus') == 1) { ?>
                     <?php echo $this->contactus(); ?>
                <?php } ?>

                <?php if ( $view_more_array != NULL ) { ?>
                    <li class="view-more">
                        <a href="#"><?php echo __('View More') ?> <i aria-hidden="true" class="fa fa-angle-down"></i></a>
                        <ul class="rootmenu-submenu topmenu_main dropdown-rightside">
                            <?php foreach ( $view_more_array as $key => $value ) { ?>
                                <li><a href="<?php echo $value?>"><?php echo $key?></a></li>
                            <?php } ?>
                        </ul>
                    </li>
                <?php } ?>

            </ul>
            <?php if( $this->act() != '' ) {
                echo $act_data = base64_decode($this->act());
            } ?>
        </nav>
    </div>
<?php } else { ?>
   
    <?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
    <?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

    <nav class="navigation" data-action="navigation">
        <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <?php /* @escapeNotVerified */ echo $_menu; ?>
            <?php /* @escapeNotVerified */ echo $block->getChildHtml(); ?>
        </ul>
    </nav>
<?php }
