<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BSS Commerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BSS Commerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    Bss_ConfigurableMatrixView
 * @author     Extension Team
 * @copyright  Copyright (c) 2015-2016 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php $_helper = $this->helper('Bss\ConfigurableMatrixView\Helper\Data');?>
<?php if ($_product->isSaleable()): ?>
	<div class="box-tocart">
		<div class="fieldset">
			<?php if ($block->shouldRenderQuantity()): ?>
				<?php if (!$_helper->isEnabled() || !$_product->getConfigurableMatrixView()): ?>
					<div class="field qty">
						<label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
						<div class="control">
							<input type="number"
							name="qty"
							id="qty"
							maxlength="12"
							value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
							title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
							data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
							/>
						</div>
					</div>
				<?php endif ?>
			<?php endif; ?>
			<div class="actions">
				<button type="submit"
				title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
				class="action primary tocart"
				id="product-addtocart-button">
				<span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
			</button>
			<?php echo $block->getChildHtml('', true) ?>
		</div>
	</div>
</div>
<?php endif; ?>
<?php if (!$_helper->isEnabled() || !$_product->getConfigurableMatrixView()): ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>
<?php else : ?>
<script>
	require([
		'jquery',
		'mage/mage',
		'Magento_Catalog/product/view/validation',
		'Bss_ConfigurableMatrixView/js/catalog-add-to-cart'
		], function ($) {
			'use strict';

			$('#product_addtocart_form').mage('validation', {
				radioCheckboxClosest: '.nested',
				submitHandler: function (form) {
					var widget = $(form).catalogAddToCart({
						bindSubmit: false
					});

					widget.catalogAddToCart('submitForm', $(form));

					return false;
				}
			});
		});
	</script>
<?php endif; ?>